field.formatter.settings.itk_azure_video_formatter:
  type: mapping
  label: 'Azure Video settings'
  mapping:
    responsive:
      type: boolean
      label: 'Responsive'
    muted:
      type: boolean
      label: 'Muted'
    autoplay:
      type: boolean
      label: 'Autoplay'
    controls:
      type: boolean
      label: 'Controls'
